# Generated by Django 3.0.5 on 2020-04-13 18:26

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256, unique=True)),
                ('description', models.TextField(max_length=1024, unique=True)),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('createAt', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=models.SET('remoted_user'), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['createAt'],
            },
        ),
        migrations.CreateModel(
            name='Ingridient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('recipes', models.ManyToManyField(to='main_app.Recipe')),
            ],
        ),
    ]
