# Generated by Django 3.0.5 on 2020-04-15 08:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='uploads/steps/%Y/%m/%d/', verbose_name='Изображение')),
                ('action', models.TextField(default=None, max_length=3024, verbose_name='Действие')),
            ],
            options={
                'verbose_name': 'Этап приготовления',
                'verbose_name_plural': 'Этапы приготовления',
            },
        ),
        migrations.AlterModelOptions(
            name='ingridient',
            options={'verbose_name': 'Ингридиент', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['createAt'], 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.RemoveField(
            model_name='ingridient',
            name='recipes',
        ),
        migrations.AddField(
            model_name='ingridient',
            name='count',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='ingridient',
            name='unit',
            field=models.CharField(blank=True, choices=[('gram', 'г'), ('kilogram', 'кг'), ('number', 'шт'), ('tablespoon', 'ст л'), ('teaspoon', 'ч л'), ('glass', 'стакан'), ('liter', 'л'), ('mililiter', 'мл'), ('tooth', 'зубок'), ('pinch', 'щепотка'), ('taste', 'по вкусу'), ('request', 'по желанию')], default='NO', max_length=10, verbose_name='Ед._изм.'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingridients',
            field=models.ManyToManyField(to='main_app.Ingridient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='procedure',
            field=models.TextField(default=None, max_length=3024, verbose_name='Порядок приготовления'),
        ),
        migrations.AlterField(
            model_name='ingridient',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Нименование'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='createAt',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(max_length=3024, unique=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=256, unique=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Steps'),
        ),
    ]
