# Generated by Django 3.0.5 on 2020-04-15 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_auto_20200415_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingridient',
            options={'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.RemoveField(
            model_name='ingridient',
            name='count',
        ),
        migrations.RemoveField(
            model_name='ingridient',
            name='unit',
        ),
        migrations.AddField(
            model_name='recipe',
            name='dish',
            field=models.CharField(choices=[('FIRST', 'ПЕРВОЕ'), ('SECOND', 'ВТОРОЕ'), ('DESSERT', 'ДЕСЕРТ'), ('SNACK', 'ЗАКУСКА'), ('FASTFOOD', 'ПЕРЕКУСИТЬ ПО БЫСТРОМУ'), ('DRINK', 'НАПИТКИ')], default='NO', max_length=10, verbose_name='Блюдо'),
        ),
        migrations.AddField(
            model_name='steps',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Номер этапа'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(max_length=5000, unique=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='procedure',
            field=models.TextField(default=None, max_length=5000, verbose_name='Порядок приготовления'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Steps', verbose_name='этапы пригтовления'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(on_delete=models.SET('remoted_user'), to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
    ]
