# Generated by Django 3.0.5 on 2020-04-15 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200415_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingridients',
        ),
    ]
