# Generated by Django 3.0.5 on 2020-04-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_recipe_ingridients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default=None, max_length=5000, verbose_name='Ингредиенты'),
        ),
    ]
