# Generated by Django 3.0.5 on 2020-04-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default=None, max_length=5000, null=True, verbose_name='Ингредиенты'),
        ),
    ]
