# Generated by Django 3.0.5 on 2020-04-18 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20200418_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['createAt'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комменетарии'},
        ),
    ]
